### ISSUE TITLE
Preprocess of the input image pair

### ISSUE THREAD

**Issue by iamcoming233** [lizhishan1997/StereoMatching_FAS#1]
Is it necessary to calibrate the image pair before it is fed into the stereo matching network?

**Comment by lizhishan1997** [comment]
In practical use, it is necessary to calibrate the image pair and then input the trained network to predict the disparity.  Since the right image in the training process is generated according to the left image and depth map (disparity map), the training input image pair can be considered to have been calibrated. As a result, it is necessary to calibrate the image pair to acquire disparity.

**Comment by lizhishan1997** [comment]
> Is it necessary to calibrate the image pair before it is fed into the stereo matching network?

In practical use, it is necessary to calibrate the image pair and then input the trained network to predict the disparity. Since the right image in the training process is generated according to the left image and depth map (disparity map), the training input image pair can be considered to have been calibrated. As a result, it is necessary to calibrate the image pair to acquire disparity
